# Generated by Django 2.1.5 on 2019-02-09 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('other_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buttons.Users')),
            ],
        ),
    ]
